initial
horseinthesky/gophermart pull request #1
Opened 2022-10-08 13:24 UTC by horseinthesky

2022-10-10 21:49 UTC, rekby commented on cmd/gophermart/main.go
> +		log.Println(err)
Тут возможно продолжение работы если вернулась ошибка?

2022-10-10 21:49 UTC, rekby commented on internal/service/storage/db.go
> +	_, err = d.conn.NamedExecContext(ctx, `INSERT INTO users (name, passhash) VALUES (:name, :passhash)`, user)
Тут может быть гонка - если одновременно придут два запроса на создание пользователя с одним логином: оба проверять что такого пользователя нет и оба добавят новую запись.

Тут нужно или добавить ограничение уникальности логина на таблицу (предпочтительно - т.к. это явное декларирование ограничения в схеме и будет работать для всех приложений подключившихся к базе)

или проверять и добавлять запись внутри одной транзакции - тогда при поступлении двух одинаковых запросов одна из транзакций завершится с ошибкой и в базе останется единственная запись.

2022-10-10 21:49 UTC, rekby commented on internal/service/storage/main.go
> +type Status int
Возможно тут будет удобнее использовать строковый тип как базовый, чтобы не заниматься преобразованиями внутри кода приложения.

2022-10-10 21:49 UTC, rekby commented on internal/service/handlers.go
> +		http.SetCookie(w,
При регистрации куку ставить не требуется. С одной стороны это не ошибка, с другой - когда код дублируется его сложно отлаживать и менять.

2022-10-10 21:49 UTC, rekby commented on internal/service/handlers.go
> +			&http.Cookie{
Такую куку очень просто подделать - т.е. просто сохранить туда ID нужного пользоватля и дальше можно выполнять запросы от его имени. Пароль можно и не знать.

Имеет смысл защищаться от изменения куки на стороне пользователя.

2022-10-10 21:49 UTC, rekby commented on internal/service/handlers.go
> +		userID, _ := strconv.Atoi(userIDString.Value)
Аутентификация пользователя по куке будет встречаться почти во всех обработчиках, посмотри как передать userID из middleware, где аутентификация уже произошла.

2022-10-10 21:49 UTC, rekby commented on internal/service/handlers.go
> +		sort.Sort(storage.OrderByDate(orders))
Данные обычно сортируются на стороне базы данных.
Сейчас это не критично (просто чуть больше кода писать), но может стать важным если потребуется постраничный вывод данных.

2022-10-10 21:49 UTC, rekby commented on internal/service/handlers.go
> +func (s *Service) handleRegister() http.HandlerFunc {
Если объявпить функцию сразу как http обработчик

```go
func (s *Service) handleRegister(w http.ResponseWriter, r *http.Request){...}
```
то потом добавлять её в обработчик можно так:
```go
r.Post("/register", s.handleRegister)
```

есть ли тут смысл усложнять и возвращать функцию из функции?

2022-10-11 13:26 UTC, horseinthesky commented on cmd/gophermart/main.go
> +		log.Println(err)
Нет, тут падаем и завершает работу. Исправил на `log.Fatal`.

2022-10-11 13:40 UTC, horseinthesky commented on internal/service/storage/db.go
> +	_, err = d.conn.NamedExecContext(ctx, `INSERT INTO users (name, passhash) VALUES (:name, :passhash)`, user)
Добавил `UNIQUE` к полю `name` в таблице `users`.

2022-10-11 13:42 UTC, horseinthesky commented on internal/service/storage/main.go
> +type Status int
Т.к. в задании определены возможные статусы, это явный кандидат на Enum.

Преобразованием занимаются методы json Marshal/Unmarshal, так что нам не нужно вообще ничего делать в коде приложения.

Это решение мне очень нравится.

2022-10-11 13:50 UTC, horseinthesky commented on internal/service/handlers.go
> +		http.SetCookie(w,
Мы же это обсуждали: в задании сказано `После успешной регистрации должна происходить автоматическая аутентификация пользователя.`.

Т.е. тут у кажется нет выбора не ставить.

2022-10-11 13:51 UTC, horseinthesky commented on internal/service/handlers.go
> +			&http.Cookie{
Да. Я хотел подумать над этим после прохождения тестов.

2022-10-11 13:57 UTC, horseinthesky commented on internal/service/handlers.go
> +		userID, _ := strconv.Atoi(userIDString.Value)
В каком-то конкретном месте посмотреть?

Я думал в middleware (раз я там хожу в базу) добавлять имя пользователя, например, также в Cookie.

2022-10-11 14:41 UTC, horseinthesky commented on internal/service/handlers.go
> +		sort.Sort(storage.OrderByDate(orders))
Добавил имя поля сортировки в сигнатуру методов интерфейса. Убрал сортировку в коде.

2022-10-11 15:26 UTC, horseinthesky commented on internal/service/handlers.go
> +func (s *Service) handleRegister() http.HandlerFunc {
В целом нет.
Это осталось с проекта metricsagent, где я предполагал возможность передачи аргументов в handler, но так и не пригодилось.

2022-10-13 16:56 UTC, horseinthesky commented on internal/service/handlers.go
> +			&http.Cookie{
Переделал аутентикацию на JWT.

2022-10-18 05:23 UTC, rekby commented on internal/service/handlers.go
> +		http.SetCookie(w,
Да, про куку ты прав.
Как тебе бысть вынести дублирующийся код ко генерированию/устновке куки в отдельный метод и из Register/Login - дёргать его.
Тогда при изменении куки не будет шанса что этот код для авторизации и логина "разъедется".

2022-10-18 05:30 UTC, rekby commented on internal/service/handlers.go
> +		userID, _ := strconv.Atoi(userIDString.Value)
Да, авторизацию лучше делать в middleware, который будет только проверять авторизацию и сохранять пользователя в запросе - для дальнейшего использования.

2022-10-18 05:41 UTC, rekby requested changes

2022-10-18 05:41 UTC, rekby commented on internal/service/middleware.go
> +		r.AddCookie(&http.Cookie{
Сохранять пользователя в куку - опасно.
Cookie - это то, что приходит от пользователя и значит пользователь может найти уязвимость в коде и прислать что-то неожиданное.


Например в данном случае пользователю достаточно просто добавить в запрос Cookie с именем user и нужным логином. Эта миддлваря добавит ещё одну куку, но потом методы внутри будут брать первое значение (которое прислал пользователь) и будут верить ему.

Т.е. внутренние данные нужно сохранять во внутренних структурах, которые не доступны для задания пользователем. В данном случае это может быть контекст запроса.

2022-10-18 16:17 UTC, horseinthesky commented on internal/service/middleware.go
> +		r.AddCookie(&http.Cookie{
Исправил. Теперь храню в контексте запроса.

2022-10-19 07:02 UTC, rekby commented on internal/service/middleware.go
> +		bodyBytes, err := io.ReadAll(r.Body)
Для защиты от DOS слишком большими запросами можно добавить чтение через io.LimitReader (опционально), чтобы не получилось просто отправлять в приложение запросы десятками гигабайт, чтобы за приложением приходил oom-killer

2022-10-23 15:29 UTC, merged